### ISSUE TITLE
Error message generated XPT file and read in PANDAS

### ISSUE THREAD

**Issue by YCK2386620654** [Roche/pyreadstat#162]
df = pd.DataFrame([{"A": 1, "B": 2}, {"A": 3, "B": 4}])
    df = df.astype("str")
    pyreadstat.write_xport(df, dst_path="aaa.xpt")
    df = pd.read_sas("aaa.xpt")

Expected behavior
Traceback (most recent call last):
  File "D:/Users/23866/test/sas/test.py", line 15, in <module>
    df = pd.read_sas("aaa.xpt")
  File "D:\Users\23866\Venv_rws_be\lib\site-packages\pandas\io\sas\sasreader.py", line 117, in read_sas
    filepath_or_buffer, index=index, encoding=encoding, chunksize=chunksize
  File "D:\Users\23866\Venv_rws_be\lib\site-packages\pandas\io\sas\sas_xport.py", line 270, in __init__
    self._read_header()
  File "D:\Users\23866\Venv_rws_be\lib\site-packages\pandas\io\sas\sas_xport.py", line 285, in _read_header
    raise ValueError("Header record is not an XPORT file.")
ValueError: Header record is not an XPORT file.

**Comment by ofajardo** [comment]
@YCK2386620654 OK this is what happens: pyreadstat writes by default XPT version 8, and it seems pandas is not prepared to read that version. You can write XPT with version 5 and then pandas can read it: 

```
df = pd.DataFrame([{"A": 1, "B": 2}, {"A": 3, "B": 4}])
df = df.astype("str")
pyreadstat.write_xport(df, dst_path="aaa.xpt", file_format_version=5)
df = pd.read_sas("aaa.xpt")
```

**Comment by YCK2386620654** [comment]
Thank you for solving my doubts
