### ISSUE TITLE
Using read_file_multiprocessing with pyreadstat.read_file_in_chunks

### ISSUE THREAD

**Issue by datalover2020** [Roche/pyreadstat#87]
Hello again my friends: 

My file seems to big for read_file_multiprocessing on my computer:
_______________this:_________
import pyreadstat
if __name__ == "__main__":
    df, meta = pyreadstat.read_file_multiprocessing(pyreadstat.read_sav, 'sample_large.sav')
    print(df.tail())
_________________ is working fine__________

Using a bigger file it fails : pyreadstat._readstat_parser.ReadstatError: Unable to open file

My idea is the file is to big for my ram and i want to use pyreadstat.read_file_multiprocessing in combination with pyreadstat.read_file_in_chunks.
Is it possible?
Or can i change the number of worker?

**Comment by ofajardo** [comment]
It should be possible to combine read in chunks and read multiprocessing but needs to be implemented first and I was already planning to do it when I get some time. 

But I would expect an out of memory error and not unable to open file so maybe it's something else.
 You are not providing enough details so I can't tell what is it
You can change the number of workers please look at the module documentation.

**Comment by datalover2020** [comment]
Im sorry realy bad manner by me.
__________________________________
Tried it with command prompt in win10, also conda and VScode.
_________________________________
script i used: 
___________________________
import pyreadstat
print('start')
if __name__ == "__main__":
    print('main:')
    df, meta = pyreadstat.read_file_multiprocessing(pyreadstat.read_sav, 'C:/Users/username/Documents/Projekte/XXX/Daten/Beispieldaten/file.sav')
    print(df.tail())
_________________
Error:
C:\Users\usernamer\Documents\Projekte\XXX\Code\file_name>python multipro.py
start
main:
Traceback (most recent call last):
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 30, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\intervaltree.pxi", line 7, in init pandas._libs.interval
ImportError: DLL load failed: The paging file is too small for this operation to complete.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usernamer\Documents\Projekte\XXX\Code\file_name\multipro.py", line 1, in <module>
    import pyreadstat
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
  File "pyreadstat\_readstat_parser.pyx", line 28, in init pyreadstat._readstat_parser
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 38, in <module>
    ) from e
ImportError: C extension: DLL load failed: The paging file is too small for this operation to complete. not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
start
start
start
start
start
start
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usernamer\Documents\Projekte\XXX\Code\file_name\multipro.py", line 1, in <module>
    import pyreadstat
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
  File "pyreadstat\_readstat_parser.pyx", line 28, in init pyreadstat._readstat_parser
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\api.py", line 15, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.base import (
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\arrays\base.py", line 28, in <module>
    from pandas.core import ops
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\__init__.py", line 22, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\ops\array_ops.py", line 13, in <module>
    from pandas._libs import Timedelta, Timestamp, lib, ops as libops
ImportError: DLL load failed: The paging file is too small for this operation to complete.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usernamer\Documents\Projekte\XXX\Code\file_name\multipro.py", line 1, in <module>
    import pyreadstat
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
  File "pyreadstat\_readstat_parser.pyx", line 28, in init pyreadstat._readstat_parser
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\groupby\generic.py", line 57, in <module>
    from pandas.core.aggregation import (
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\aggregation.py", line 27, in <module>
    from pandas.core.series import FrameOrSeriesUnion, Series
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\series.py", line 68, in <module>
    from pandas.core import algorithms, base, generic, nanops, ops
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
MemoryError
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usernamer\Documents\Projekte\XXX\Code\file_name\multipro.py", line 1, in <module>
    import pyreadstat
Traceback (most recent call last):
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 30, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\_libs\__init__.py", line 13, in <module>
  File "pyreadstat\_readstat_parser.pyx", line 28, in init pyreadstat._readstat_parser
    from pandas._libs.interval import Interval
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 11, in <module>
ImportError: DLL load failed: The paging file is too small for this operation to complete.
    __import__(dependency)

The above exception was the direct cause of the following exception:

  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 138, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    from . import _distributor_init
    prepare(preparation_data)
    prepare(preparation_data)
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
    run_name="__mp_main__")
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    WinDLL(os.path.abspath(filename))
    exec(code, run_globals)
    exec(code, run_globals)
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
  File "C:\Users\usernamer\Documents\Projekte\XXX\Code\file_name\multipro.py", line 1, in <module>
  File "C:\Users\usernamer\Documents\Projekte\XXX\Code\file_name\multipro.py", line 1, in <module>
    import pyreadstat
    import pyreadstat
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
  File "pyreadstat\_readstat_parser.pyx", line 28, in init pyreadstat._readstat_parser
  File "pyreadstat\_readstat_parser.pyx", line 28, in init pyreadstat._readstat_parser
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 38, in <module>
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 52, in <module>
    ) from e
    from pandas.core.api import (
ImportError: C extension: DLL load failed: The paging file is too small for this operation to complete. not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\api.py", line 15, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\usernamer\AppData\Roaming\Python\Python37\site-packages\pandas\core\arrays\__init__.py", line 7, in <module>
    self._handle = _dlopen(self._name, mode)
    from pandas.core.arrays.categorical import Categorical
OSError: [WinError 1455] The paging file is too small for this operation to complete
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
MemoryError
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\site-packages\pyreadstat\worker.py", line 24, in worker
    df, meta = read_function(path, row_offset=offset, row_limit=chunksize, **kwargs)
  File "pyreadstat\pyreadstat.pyx", line 328, in pyreadstat.pyreadstat.read_sav
  File "pyreadstat\_readstat_parser.pyx", line 1000, in pyreadstat._readstat_parser.run_conversion
  File "pyreadstat\_readstat_parser.pyx", line 838, in pyreadstat._readstat_parser.run_readstat_parser
  File "pyreadstat\_readstat_parser.pyx", line 768, in pyreadstat._readstat_parser.check_exit_status
pyreadstat._readstat_parser.ReadstatError: Unable to open file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multipro.py", line 9, in <module>
    df, meta = pyreadstat.read_file_multiprocessing(pyreadstat.read_sav, 'C:/Users/usernamer/Documents/Projekte/XXX/Daten/Beispieldaten/my_big_sav.sav')
  File "pyreadstat\pyreadstat.pyx", line 623, in pyreadstat.pyreadstat.read_file_multiprocessing
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\usernamer\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
pyreadstat._readstat_parser.ReadstatError: Unable to open file

_______________________________________

So there is also an memory error in it.
Thank you so much for your time!

**Comment by ofajardo** [comment]
Ok. What happens when you decrease the number of workers? Use the parameter num_processes=x where x is an integer.

**Comment by ofajardo** [comment]
Also: the page size can be increased:

Programmatically:
https://github.community/t/error-the-paging-file-is-too-small-for-this-operation-to-complete/17141
Gui:
https://communities.bentley.com/products/hydraulics___hydrology/w/hydraulics_and_hydrology__wiki/13358/paging-file-is-too-small-for-this-operation-to-complete

BTW, how big is your file in terms of number of columns x number of rows?

**Comment by datalover2020** [comment]
Thank you!

size  = 13.7Mil*43 (250mb, mixed)
->This is one of the smaller files i have. 
I will try you ideas later to day.

**Comment by ofajardo** [comment]
OK I have released version 1.0.4 and there I have adapted read_file_in_chunks to use multiprocessing, you have to use the argument multiprocessing=True. Also now num_processes is by default 4. Check the documentation:
https://ofajardo.github.io/pyreadstat_documentation/_build/html/index.html

I have the feeling that this anyway fail due to the small page size on windows. Maybe the final solution is to increase that.

Please let me know how it goes.

**Comment by datalover2020** [comment]
Hey,
interesting findings: 
 - increasing page size didnt help
 - tested with command prompt WIN10, python 3.7.9 -> for 1.04: 
sample.sav runs with chunk+mulit, but it does not work every single time, sometimes it fails multiple times before it works again, it does not appear to correlate with time waited before executing again. 50/50 Chance for it to work.
Change chunksize: 1 or 100.000 or 1.000.000 didnt not change the odds for success. 
 
I will keep you updated.

**Comment by ofajardo** [comment]
That's bad ... If you use some other python version (3.8) does it improve?

**Comment by ofajardo** [comment]
Ok I think I know what's happening.

Hi @jonathon-love ! I built a new function to read the files in parallel using python multiprocessing. It's working like a charm in unix but on windows a misterious "unable to open file" error appears intermittently.

I noticed that on the custom open function for windows we have a _SH_DENYRD. I'm thinking that the processes are racing to get access to the file. What could happen if I change to _SH_DENYWR? Is it thread safe? Why do you have deny read instead of deny read and write or just deny write as I want?

This is what we have right now:

https://github.com/Roche/pyreadstat/blob/master/pyreadstat/_readstat_parser.pyx#L748

Docs:

https://docs.microsoft.com/en-us/cpp/c-runtime-library/sharing-constants?view=msvc-160

**Comment by jonathon-love** [comment]
hey,

i agree ... looking at this with fresh eyes, _SH_DENYRD seems like a poor choice :P _SH_DENYWR looks like what we want here.

cheers

**Comment by jonathon-love** [comment]
i'm surprised a multiprocess approach yields much advantage, what do your benchmarks tell you? i would have thought these processes to be so IO bound that you wouldn't get much of a speed-up. i would have approached it using asyncio and a non-blocking file reading library -- not saying you shouldn't do it the way you have, only that it sounds like something is at odds with my understanding, you're about to explain it, and i'm about to learn something new :)

**Comment by ofajardo** [comment]
Aha! Probably you're right ... I typically handle cpu bound problems so I went for multiprocessing with the eyes closed. Even using a lot of cores (16) I gain max 3x. 
Could you point me at any example of the approach you are proposing? Why is it necessary to use a separate non blocking reading library instead of just _wsopen?
Thanks!

**Comment by ofajardo** [comment]
And to reason about my choice for multiprocessing ... my profilings says that most of the time is spent casting from c to python types and next manipulating numpy arrays rather than reading the file ... So I thought that would be cpu bound ... But maybe I am interpreting the profiling wrong and most of the time it's spent nit on conversion but on handle_value which is reading? Worth checking

**Comment by jonathon-love** [comment]
so i think you'd still use _wsopen, but you'd pass the file descriptor onto something like the `aiofile` and/or `aiofiles` projects (i've never used these). however, an asyncio approach, although nice, is probably not worth breaking compatibility with earlier pythons.

so i think a threading approach might be a good solution. if your profiling says that time is spent casting between c and python types, it may still be a good candidate for threads, as i think when your code enters native code like that it releases the GIL.

it may potentially only be a small number of changes too - but it should bring down your memory footprint, and (i would predict) a performance boost (because communication between threads is much quicker) -- but it's an empirical question!

jonathon

**Comment by ofajardo** [comment]
Right, my first intention was to go for threads, but apparently in order to release the GIL the cython code must use exclusively C types and I have places where I need python types (for example numpy arrays of type objects are not automatically convertable to C arrays via memory views), it would be really difficult to get rid of these structures. That's why I went for multiprocessing as it's low hanging fruit. 

Have you been able to release the Gil under these circumstances? I was checking this: 
https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html
Oh another thing I don't like is that it requires openmp which is going to be a headache with precompiled wheels as I am providing.


But I'll check python asyncio ... Maybe it does something good ... Altough with the Gil in the middle I am not sure ...

**Comment by jonathon-love** [comment]
ah ok. it sounds like you know more about this that me ...

**Comment by ofajardo** [comment]
I'll play with your ideas to see if it goes somewhere, in the meantime I'm going to fix _SH_DENYWR ... multiprocessing is not a super boost, but 3 times improvement is better than nothing. thanks for all the ideas!

**Comment by ofajardo** [comment]
and btw, just in case it is of help for jamovi: when writing we are also using _SH_DENYRD and I think it should be either _SH_DENYRW or _SH_SECURE. Since I am not going to write concurrently or going to read while writing I am going to try _SH_DENYRW.

**Comment by ofajardo** [comment]
@datalover2020 the fix is in the new version 1.0.5, it looks better. Can you please test and see if now it works for you?

**Comment by datalover2020** [comment]
Works like a charm with version 1.05.
Thank you so much.
